title = "Ewen Lallinec"
baseURL = "https://elallinec.github.io"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = true          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id
enableRobotsTXT = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[params]
  author = "Ewen Lallinec"
  description = "Personal website of Ewen Lallinec, made using Hugo template for researcher."
  favicon = "MyIcon.ico"  # path to a .ico to use as favicon
  logo = "MyIcon.ico"  # url or path to a logo to put in the header
  [params.footer]
    text = "By Ewen Lallinec"
    url = "https://github.com/ELallinec"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "110px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "Github"
    url = "https://github.com/ELallinec"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:ewen.lallinec@universite-paris-saclay.Fr"
  #[[params.socialIcons]]
    #icon = "ai ai-google-scholar"
    #title = "Scholar"
    #url = "https://scholar.google.com/"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Research"
    url = "/research"
    weight = 1
  [[menu.main]]
    name = "Teaching"
    url = "/teaching"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3
  
  
[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
